# Twitter handles sourced from patrickcollison.com/people
# People without Twitter links are omitted (Scott Aaronson, Sarah Constantin, Alan Kay)

PEOPLE = [
    {"name": "Scott Alexander",     "handle": "slatestarcodex"},
    {"name": "Marc Andreessen",     "handle": "pmarca"},
    {"name": "John Arnold",         "handle": "JohnArnoldFndtn"},
    {"name": "Ava",                 "handle": "noampomsky"},
    {"name": "Juan Benet",          "handle": "juanbenet"},
    {"name": "Stewart Brand",       "handle": "stewartbrand"},
    {"name": "Vitalik Buterin",     "handle": "VitalikButerin"},
    {"name": "Bryan Caplan",        "handle": "bryan_caplan"},
    {"name": "Matt Clancy",         "handle": "mattsclancy"},
    {"name": "Michael Clemens",     "handle": "m_clem"},
    {"name": "John Collison",       "handle": "collision"},
    {"name": "Tyler Cowen",         "handle": "tylercowen"},
    {"name": "Adam D'Angelo",       "handle": "adamdangelo"},
    {"name": "Saloni Dattani",      "handle": "salonium"},
    {"name": "Laura Deming",        "handle": "laurademing"},
    {"name": "David Deutsch",       "handle": "DavidDeutschOxf"},
    {"name": "Joe Edelman",         "handle": "edelwax"},
    {"name": "Nadia Eghbal",        "handle": "nayafia"},
    {"name": "James Fallows",       "handle": "JamesFallows"},
    {"name": "Caitlin Flanagan",    "handle": "CaitlinPacific"},
    {"name": "Conor Friedersdorf",  "handle": "conor64"},
    {"name": "Nat Friedman",        "handle": "natfriedman"},
    {"name": "Julia Galef",         "handle": "juliagalef"},
    {"name": "Elad Gil",            "handle": "eladgil"},
    {"name": "Paul Graham",         "handle": "paulg"},
    {"name": "Tanner Greer",        "handle": "Scholars_Stage"},
    {"name": "Daniel Gross",        "handle": "danielgross"},
    {"name": "Gwern",               "handle": "gwern"},
    {"name": "Sarah Haider",        "handle": "SarahTheHaider"},
    {"name": "Robin Hanson",        "handle": "robinhanson"},
    {"name": "Anton Howes",         "handle": "antonhowes"},
    {"name": "Kevin Kelly",         "handle": "kevin2kelly"},
    {"name": "Arnold Kling",        "handle": "KlingBlog"},
    {"name": "Casey Handmer",       "handle": "CJHandmer"},
    {"name": "Mason Hartman",       "handle": "webdevmason"},
    {"name": "Claire Lehmann",      "handle": "clairlemon"},
    {"name": "Daniel Lemire",       "handle": "lemire"},
    {"name": "Nathan Lewis",        "handle": "NathanNWE"},
    {"name": "Derek Lowe",          "handle": "Dereklowe"},
    {"name": "Andy Matuschak",      "handle": "andy_matuschak"},
    {"name": "Megan McArdle",       "handle": "asymmetricinfo"},
    {"name": "Niko McCarty",        "handle": "NikoMcCarty"},
    {"name": "Patrick McKenzie",    "handle": "patio11"},
    {"name": "Michael Nielsen",     "handle": "michael_nielsen"},
    {"name": "Kelsey Piper",        "handle": "KelseyTuoc"},
    {"name": "Pseudoerasmus",       "handle": "pseudoerasmus"},
    {"name": "José Luis Ricón",     "handle": "artirkel"},
    {"name": "Max Roser",           "handle": "MaxCRoser"},
    {"name": "Kevin Simler",        "handle": "kevinsimler"},
    {"name": "Michael Solana",      "handle": "micsolana"},
    {"name": "Noah Smith",          "handle": "noahpinion"},
    {"name": "Riva Tez",            "handle": "rivatez"},
    {"name": "Ben Thompson",        "handle": "benthompson"},
    {"name": "Derek Thompson",      "handle": "DKThomp"},
    {"name": "Eric Topol",          "handle": "EricTopol"},
    {"name": "Des Traynor",         "handle": "destraynor"},
    {"name": "Bret Victor",         "handle": "worrydream"},
    {"name": "Dan Wang",            "handle": "danwwang"},
    {"name": "Eugene Wei",          "handle": "eugenewei"},
    {"name": "Tamara Winter",       "handle": "_tamarawinter"},
    {"name": "Stephen Wolfram",     "handle": "stephen_wolfram"},
    {"name": "Devon Zuegel",        "handle": "devonzuegel"},
]
